databases:
  - name: tour-hunter-backend
    databaseName: tour_hunter_production
    user: menge

services:
  - type: web
    name: tour-hunter-backend
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tour-hunter-backend
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
